### PR TITLE
Merge pull request #15 from rami0r/main

### PR DESCRIPTION
**Pull request by rami-HP**
Main

### CODE REVIEW

**Review by rami-HP — COMMENTED** [review]
https://vscode.dev/github/ramihp/hello-world/blob/c7cbb126a44b5b78b76af4ca360722c1c78e5546b/workflows/codeql-analysis.yml#L22

**Comment by rami0r** [comment]
commit

**Comment by rami-HP** [comment]
> commit

**Review by rami-HP — COMMENTED** [review]
Pull Request

**Pull request merged**
